spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lxj123456
#    password: root
    url: jdbc:mysql://120.79.223.83:3306/wxshop?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
#    url: jdbc:mysql://localhost:3306/myshop?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

server:
  port: 8090

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.edu.guet.backendmanagement.bean
#  将数据库表的下划线转成驼峰（Mapper）
  configuration:
    map-underscore-to-camel-case: true